// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


package org.usfirst.frc2877.UltimateAscent2013Robot.subsystems;

import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;
import org.usfirst.frc2877.UltimateAscent2013Robot.RobotMap;


/**
 *
 */
public class Shooter extends Subsystem {
    
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    CANJaguar shooterFrontWheel = RobotMap.shooterFrontWheel;
    CANJaguar shooterBackWheel = RobotMap.shooterBackWheel;

    // Constants to define the minimum and maximum angles for the shooter.
    // TODO: These must be updated once we make the measurements
    // This is the minimum voltage from the sensor when the shooter is at
    // it's minimum angle
    
               
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    
    public void Shooter() {
        System.out.println("Shooter constructed.");
    }

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    
    public void runShooter(boolean enable) {
        double frontWheel = 0.0, backWheel = 0.0;  
        if (enable) {
            frontWheel = -1.0;
            backWheel = -0.72;
        }
        
        try {
            RobotMap.shooterFrontWheel.setX(frontWheel);
            RobotMap.shooterBackWheel.setX(backWheel);
        } catch (Exception ex) {
            System.out.println("Shooter motors speed set failed");
        }
    }
        
    
   
}

