// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


package org.usfirst.frc2877.UltimateAscent2013Robot;

import com.sun.squawk.microedition.io.FileConnection;
import edu.wpi.first.wpilibj.IterativeRobot;
import edu.wpi.first.wpilibj.Relay;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.command.Scheduler;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.can.CANTimeoutException;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import java.io.DataInputStream;
import javax.microedition.io.Connector;
import org.usfirst.frc2877.UltimateAscent2013Robot.commands.*;
import org.usfirst.frc2877.UltimateAscent2013Robot.subsystems.*;

/**
 * The VM is configured to automatically run this class, and to call the
 * functions corresponding to each mode, as described in the IterativeRobot
 * documentation. If you change the name of this class or the package after
 * creating this project, you must also update the manifest file in the resource
 * directory.
 */
public class Robot extends IterativeRobot {

    Command autonomousCommand;

    public static OI oi;
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static DriveTrain driveTrain;
    public static Shooter shooter;
    public static ShooterAngleControl shooterAngleControl;
    public static Acquisition acquisition;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private Drive drive;
    private ShooterAngleCommand shooterAngleCommand;
    public static int m_total_ticks = 0;
    public static boolean m_shooter_enable = false;
    
    // This constant is used to define how many cycles we need to go to make
    // sure that the cam has cleared the limit switch
    public static final String OVERSHOOT_FILE = "file:///overshoot.txt";
    public static int OVERSHOOT_AMOUNT_UP = 3;
    public static int OVERSHOOT_AMOUNT_DOWN = 1;
    
    public static AcquisitionScrewControl autoUpOne;
    public static AcquisitionScrewControl autoDownOne;
    public static boolean m_lift_emergency_stop = false;


    /**
     * This function is run when the robot is first started up and should be
     * used for any initialization code.
     */
    public void robotInit() {
	RobotMap.init();
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrain = new DriveTrain();
        shooter = new Shooter();
        shooterAngleControl = new ShooterAngleControl();
        acquisition = new Acquisition();
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        drive = new Drive();
        shooterAngleCommand = new ShooterAngleCommand();
        readOvershoot();

        // This MUST be here. If the OI creates Commands (which it very likely
        // will), constructing it during the construction of CommandBase (from
        // which commands extend), subsystems are not guaranteed to be
        // yet. Thus, their requires() statements may grab null pointers. Bad
        // news. Don't move it.
        oi = new OI();
	
        // We need to initialize the disk positions
        // This is our presumed automous setup
        Acquisition.diskPositions[4] = false;
        Acquisition.diskPositions[3] = true;
        Acquisition.diskPositions[2] = true;
        Acquisition.diskPositions[1] = true;
        Acquisition.diskPositions[0] = false;
        Acquisition.m_highestDisk = 3;
        Acquisition.m_lowestDisk = 1;
        Acquisition.m_numDisks = 3;
        updateDashboard();
        
        autoUpOne = new AcquisitionScrewControl(1,true);
        autoDownOne = new AcquisitionScrewControl(1,true);
        
        // instantiate the command used for the autonomous period
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS
        autonomousCommand = new AutonomousCommand();
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS
    }

    public void autonomousInit() {
        // schedule the autonomous command (example)
        if (autonomousCommand != null)
        {
            autonomousCommand.start();
        }
    }

    /**
     * This function is called periodically during autonomous
     */
    public void autonomousPeriodic() {
        Scheduler.getInstance().run();
        commonPeriodic();
     }

    public void teleopInit() {
	// This makes sure that the autonomous stops running when
        // teleop starts running. If you want the autonomous to 
        // continue until interrupted by another command, remove
        // this line or comment it out.
        System.out.println("teleopInit");
        if (autonomousCommand != null) { autonomousCommand.cancel(); }
        // start the drive command.  This will remain active during teleop
        drive.start();
        ShooterEnable shooterEnable = new ShooterEnable(true);
        shooterEnable.start();
        // create and start the shooterElevationControl command 
        shooterAngleCommand.start();
        // The initialize method of the acquisition roller will toggle it on
        oi.roller.start();
    }

    /**
     * This function is called periodically during operator control
     */
    public void teleopPeriodic() {
        Scheduler.getInstance().run();
        commonPeriodic();
    }
    
    private void commonPeriodic() {
        m_total_ticks++;
        // check the shooter elevation angle
        shooterAngleControl.shooterElevationAngle();
        
        // Check our acquisition sensors.
        // returns 1 if we need to lift a disk, -1 if we need to lower
        // and 0 if there's nothing to do
        switch (acquisition.refreshValues())
        {
            case 1:
                autoUpOne.start();
                break;
            case -1:
                autoDownOne.start();
                break;
            case 0:
                break;
        }

        updateDashboard();
    }

    /**
     * This function called periodically during test mode
     */
    public void testPeriodic() {
        LiveWindow.run();
    }
    
    // update frequency in times per second
    public static final int FREQUENCY = 10;
    public static final int TICKS_PER_SECOND = 50;
    public static int m_count = TICKS_PER_SECOND/FREQUENCY;
    public static void updateDashboard()
    {
         
        if (--m_count==0)
        {
            m_count = TICKS_PER_SECOND/FREQUENCY;
            SmartDashboard.putNumber("Ticks", m_total_ticks);

            RobotMap.jags.UpdateDashboard();
            double lift_current = RobotMap.jags.jags[8].m_current;
            if (lift_current > 4.0) {
                try {
                    RobotMap.jags.jags[8].m_jag.setX(0.0);
                    acquisition.m_direction = 0;
                    autoUpOne.m_direction = 0;
                    autoDownOne.m_direction = 0;
                    oi.screwDownOne.m_direction = 0;
                    oi.screwUpOne.m_direction = 0;
                } catch (Exception ex) {
                    System.out.println("Lift can't stop: " + ex.getMessage());
                }
                System.out.println("LIFT EMERGENCY STOP!!!!!!! - " + lift_current);
                m_lift_emergency_stop = true;
            }
              
            // 
            double compassAngle = 83-Robot.shooterAngleControl.currentShooterAngle/3;
            SmartDashboard.putBoolean("LIFT OVERCURRENT", !m_lift_emergency_stop);
            SmartDashboard.putNumber("Shooter compass", compassAngle);
            SmartDashboard.putNumber("Shooter angle", Robot.shooterAngleControl.currentShooterAngle);
            SmartDashboard.putNumber("Shooter angle volts", Robot.shooterAngleControl.shooterElevationVoltage);

            SmartDashboard.putBoolean("Disk 0", Acquisition.diskPositions[0]);
            SmartDashboard.putBoolean("Disk 1", Acquisition.diskPositions[1]);
            SmartDashboard.putBoolean("Disk 2", Acquisition.diskPositions[2]);
            SmartDashboard.putBoolean("Disk 3", Acquisition.diskPositions[3]);
            SmartDashboard.putBoolean("Disk 4", Acquisition.diskPositions[4]);

            SmartDashboard.putNumber("Lowest disk", Acquisition.m_lowestDisk);
            SmartDashboard.putNumber("Highest disk", Acquisition.m_highestDisk);

            SmartDashboard.putNumber("OVERSHOOT_AMOUNT_UP", OVERSHOOT_AMOUNT_UP);
            SmartDashboard.putNumber("OVERSHOOT_AMOUNT_DOWN", OVERSHOOT_AMOUNT_DOWN);
            SmartDashboard.putBoolean("Top switch", !RobotMap.topAcquisitionSwitch.get());
            SmartDashboard.putBoolean("Bottom switch", !RobotMap.bottomAcquisitionSwitch.get());
            
            SmartDashboard.putBoolean("Acquisition roller", 
                    RobotMap.acquisitionRoller.get()==Relay.Value.kForward ? true : false);
            
            SmartDashboard.putBoolean("Shooter enable", m_shooter_enable);
                
        }
  
        
    }
    
    public static void debugOut(String label, String value)
    {
        System.out.println(label + " " + value);
        SmartDashboard.putString(label, value);
    }
    
    public static void debugOutBoolean(String label, boolean value)
    {
        System.out.println(label + " " + (value ? "true" : "false"));
        SmartDashboard.putBoolean(label, value);
    }

    public static void debugOutNumber(String label, double number)
    {
        System.out.println(label + " " + number);
        SmartDashboard.putNumber(label, number);
    }
    
    public boolean readOvershoot() {
        try {
            // Persist our overshoot numbers to a file
            DataInputStream file;
            FileConnection fc;

            fc = (FileConnection)Connector.open(OVERSHOOT_FILE, Connector.READ);
            if (fc.exists()) {
                file = fc.openDataInputStream();
                System.out.println("Loading " + OVERSHOOT_FILE);
                OVERSHOOT_AMOUNT_UP = file.readInt();
                System.out.println(OVERSHOOT_AMOUNT_UP);
                OVERSHOOT_AMOUNT_DOWN = file.readInt();
                System.out.println(OVERSHOOT_AMOUNT_DOWN);
                file.close();
                fc.close();
            }
            else { System.out.println("No overshoot.txt"); }
        }
        catch (Exception ex) {
            System.out.println("File output error: " + ex.getMessage());
        }


        return true;
    }
}
